In [1]:
import numpy as np
import tensorflow as tf

In [ ]:
# random value from a random distribution between [0,1)
np.random.rand()

In [5]:
import h5py #https://www.geeksforgeeks.org/hdf5-files-in-python/
#read h5 dataset file 
dataset1 = h5py.File("datasets/train_signs.h5","r")
#pointing to 'train_set_x' in dataset1
d1 = dataset1["train_set_x"]

In [108]:
#if data already exists in form of tensor objecct, python list or numpy array .from_tensor_slices
# can convert it into a dataset.
ds1 = tf.data.Dataset.from_tensor_slices(d1) 
##iterate over dataset
# for i in ds1:
#     print(i)

In [115]:
#divide dataset into batches
ds2 = tf.data.Dataset.from_tensor_slices([1,45,6,8,9.0,89.0,7,9])
b1 = ds2.batch(3)
for i in b1:
    print(i.numpy())

[ 1. 45.  6.]
[ 8.  9. 89.]
[7. 9.]


In [24]:
#convert a numpy array into tensor 
arr1 = np.array([range(5)])
t1 = tf.convert_to_tensor(arr1)
print(t1.numpy()) # numpy() to display

[[0 1 2 3 4]]


In [51]:
y_true = [[0, 1, 0], [0, 0, 1]]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
# Using 'auto'/'sum_over_batch_size' reduction type.
cce = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred).numpy()
cce


1.1769392

In [61]:
#categorial cross entropy loss function
y_true = [[1,0,0],[0,1,0]]
y_pred = [[.8,.1,.1],[0.9,0.05,0.05]]
a = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
print(a.numpy())

y_true = [[1,0],[0,1]]
y_pred  = [[ 2.4048107,   5.0334096 ],[-0.7921977,  -4.1523376 ]]
b = tf.keras.losses.categorical_crossentropy(y_true,y_pred,from_logits=True) # y_pred is a unnormalized vector(logits vector)
# then from_logits=True
print("\n",b.numpy())

[0.22314355 2.9957323 ]

 [2.6982925 3.394281 ]


In [96]:
# tf.GradientTape and tf.Variable
x = tf.Variable([1,2.0,3]) #tf.Variable specify recordable variables, without it GradientTape won't work 
#atleast one entry should be float (probabily a bug)
with tf.GradientTape(persistent=True) as gt: #if you want to calculate with respect to #more than one variable persistent=True 
    y = x**4
    loss = tf.reduce_mean(np.log(y)+x**3)
print("Gradient of x with respect to loss",gt.gradient(loss,x).numpy(),
      "\nGradient of x with respect to y",gt.gradient(y,x).numpy())

Gradient of x with respect to loss [1. 4. 9.] 
Gradient of x with respect to y [  4.  32. 108.]


In [23]:
#make tensor of 1's
t_ones = tf.ones([5,3])
print(t_ones.numpy())

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
#make tensor of constants
t_const = tf.constant([1.33,4,0,8,np.pi],dtype=tf.float32)
print(t_const.numpy())

[1.33      4.        0.        8.        3.1415927]


In [47]:
#change datatype of tensor
t_32 = tf.constant([98,8,9.9],dtype=tf.float32)
t_64 = tf.cast(t_32,dtype=tf.float64)
print(t_64)

tf.Tensor([98.          8.          9.89999962], shape=(3,), dtype=float64)


In [50]:
#transpose a tensor
t2 = tf.random.uniform([5,3])
t3 = tf.transpose(t2)
print(t2.shape," --> ",t3.shape)

(5, 3)  -->  (3, 5)


In [55]:
#reshape a vector
t4 = tf.random.normal([4,5])
t_reshape = tf.reshape(t4,shape=(2,10))
print(t4.shape," --> ",t_reshape.shape)

(4, 5)  -->  (2, 10)


In [61]:
#elementwise multiply tensor
t5 = tf.random.uniform(shape=(4,3),maxval=3,minval=1)
t6 = tf.random.normal(shape=(4,3),mean=0,stddev=1)#std normal distribution
tf.multiply(t5,t6).numpy()

array([[ 0.414394  , -1.1486506 ,  2.1187453 ],
       [-1.1296043 , -0.89172375, -0.20756957],
       [-0.19543427,  2.074313  ,  0.63056356],
       [-0.96307576,  1.6300067 , -1.807727  ]], dtype=float32)

In [78]:
#matrix multiplication of tensors
np.set_printoptions(precision=2)
t8 = tf.random.uniform(shape=(3,5))
t10 = tf.random.normal(shape=(5,3))
t9 = tf.random.normal(shape=(3,5))
t7 = tf.linalg.matmul(t8,t10)
print(t7.numpy())

t11 = tf.linalg.matmul(t8,t9,transpose_a=True) #transpose first tensor and multiply
print("\n",t11.numpy())

t12 = tf.linalg.matmul(t8,t9,transpose_b=True)
print("\n",t12.numpy())

[[ 0.19  0.95 -0.8 ]
 [-0.4   1.43  0.55]
 [ 0.53  1.69 -0.93]]

 [[ 0.23  0.5   0.45  0.42  0.52]
 [ 0.3   0.71  0.59  0.63  0.66]
 [-0.39  1.22  0.78  0.18  0.74]
 [-0.63  2.14  1.    0.61  0.83]
 [ 0.49  0.42  0.64  0.53  0.81]]

 [[0.56 0.6  0.88]
 [0.03 1.06 1.73]
 [0.64 1.17 1.51]]


In [83]:
#mean, sum, stddev
t10 = tf.random.normal(shape=(5,3))
t13 = tf.math.reduce_mean(t10,axis=1,keepdims=True) #mean along y axis
print(t13.numpy())

[[-1.34e-04]
 [-1.21e+00]
 [ 4.22e-01]
 [ 6.26e-01]
 [ 1.75e-01]]


In [100]:
#split tensors
t14 = tf.random.uniform((12,))
t15 = tf.split(t14,num_or_size_splits=4) #splits tensor into a list of 4 tensors
print(tf.squeeze(t15),"\n")
t16 = tf.split(t14,num_or_size_splits=[6,6]) #splits by size provided of output tensor
print(tf.squeeze(t16),"\n")

tf.Tensor(
[[0.48 0.03 0.19]
 [0.41 0.41 0.04]
 [0.13 0.74 1.  ]
 [0.36 0.02 0.86]], shape=(4, 3), dtype=float32) 

tf.Tensor(
[[0.48 0.03 0.19 0.41 0.41 0.04]
 [0.13 0.74 1.   0.36 0.02 0.86]], shape=(2, 6), dtype=float32) 



In [106]:
#stack tensors
t17 = tf.zeros((3,))
t18 = tf.ones((3,))
tf.stack([t17,t18],axis=0).numpy()

array([[0., 0., 0.],
       [1., 1., 1.]], dtype=float32)

In [4]:
import tensorflow.keras.layers as tfl

In [21]:
arr1 = np.arange(25).reshape(5,5)
model = tf.keras.Sequential([
    tf.keras.Input(shape=(2,2)),
    tfl.Dense(2),
    tfl.BatchNormalization(axis=1)])
print(len(model.weights)) #each dense layer adds in length (weights,biases)

[<tf.Variable 'dense_2/kernel:0' shape=(2, 2) dtype=float32, numpy=
 array([[-0.35828698,  0.83551395],
        [-0.3050661 , -0.11688697]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_9/gamma:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>,
 <tf.Variable 'batch_normalization_9/beta:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_9/moving_mean:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_9/moving_variance:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>]